Verify deployments input DEVOPS-8235

diff --git a/.github/workflows/schedule-deployment.yml b/.github/workflows/schedule-deployment.yml
--- a/.github/workflows/schedule-deployment.yml
+++ b/.github/workflows/schedule-deployment.yml
@@ -26,8 +26,34 @@ jobs:
           DEPLOYMENTS: ${{ inputs.deployments }}
         shell: bash
         run: |
-          IFS=', ' read -r -a deployments <<< "${DEPLOYMENTS}"
-          declare -p deployments
+          IFS=', ' read -r -a deployments <<< "${DEPLOYMENTS//[[:blank:]]/}"
+          # declare -p deployments
+          declare -a errors
           for deployment in "${deployments[@]}"; do
-            echo "deployment=${deployment}|"
+            echo "deployment=${deployment}"
+            if [[ ! "${deployment}" =~ : ]]; then
+              errors+=("Missing colon delimiter in deployment '${deployment}'.")
+              continue
+            fi
+            matchkey=$(echo "${deployment}" | cut -d ':' -f 1)
+            echo "matchkey=${matchkey}"
+            if ! [ -d "js/matchkeys/${matchkey}" ]; then
+              errors+=("The matchkey '${matchkey}' is not found.")
+            fi
+            sha=$(echo "${deployment}" | cut -d ':' -f 2)
+            echo "sha=${sha}"
+            if [ -z "${sha}" ]; then
+              errors+=("The SHA is missing for matchkey '${matchkey}'.")
+              continue
+            fi
+            branch=$(git name-rev --name-only "${sha}" 2>&1 | sed 's/~.*$//')
+            if [[ "${branch}" =~ .*"Could not get".* ]]; then
+              errors+=("Could not find SHA '${sha}'.")
+              continue
+            fi
+            echo "branch=${branch}"
           done
+          if [ ${#errors[@]} -gt 0 ]; then
+            printf "ERROR: %s\n" "${errors[@]}"
+            exit 1
+          fi
